version: 2

shared: &shared
  steps:
    - run:
        name: Install required runtime dependencies
        command: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends git
          pip install --upgrade tox
    - checkout
    - run:
        name: Execute tests through tox
        command: tox

jobs:
  "python-2.7":
    <<: *shared
    docker:
      - image: python:2.7-slim
  "python-3.4":
    <<: *shared
    docker:
      - image: python:3.4-slim
  "python-3.5":
    <<: *shared
    docker:
      - image: python:3.5-slim
  "python-3.6":
    <<: *shared
    docker:
      - image: python:3.6-slim
  "python-3.7":
    <<: *shared
    docker:
      - image: python:3.7-slim

workflows:
  version: 2
  build:
    jobs:
      - "python-2.7"
      - "python-3.4"
      - "python-3.5"
      - "python-3.6"
      - "python-3.7"
